name: GitHub Actions

on: [push]

jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v3
        with: 
          token: ${{github.token}}
      - name: list directories
        run: |
          echo $GITHUB_REPOSITORY
          echo "${{github.token}}"
          ls -a